[package]
name = "k"
version = "0.1.1"
authors = ["singaraiona <singaraiona@gmail.com>"]

[[bin]]
name="k"
path="src/app/repl.rs"

[dependencies]
lazy_static = "0.2.2"
regex = "0.2"
itertools = "0.5.9"